modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   authors="${mod_authors}"
   logoFile='logo.png'
   logoBlur=false

description='''${mod_description}'''
[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="geckolib"
   mandatory=true
   versionRange="[4.2,)"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="irons_spellbooks"
   mandatory=true
   versionRange="[1.20.1-3.0.0,1.20.1-4.0.0)"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="blatium"
   mandatory=true
   versionRange="[0.1,)"
   ordering="NONE"
   side="BOTH"